/**
 * Study content (commentary) for Psalms 51–70, keyed by chapter number.
 * Same shape as other files in this directory; consumed by
 * scripts/build-psalms-range.mjs to build chapter-data JSON + MD/PDF.
 */
export const STUDIES = {
  51: {
    title: `Create in Me a Clean Heart`,
    subtitle: `Create in me a clean heart, O God`,
    context: `Superscription: to the chief musician, a psalm of David, when Nathan the prophet came unto him, after he had gone in to Bathsheba (2 Sam 11–12). This is the greatest of the seven penitential psalms. Henry calls it a pattern for true repentance: conviction of sin, plea for mercy, confession, longing for renewal, and resolve to teach others. MacArthur-style notes stress that David does not minimize his guilt (adultery and murder) yet appeals wholly to God's "lovingkindness" and "tender mercies," never to his own righteousness. The psalm moves from forgiveness (1–9) to renewal (10–12) to restored usefulness and worship (13–19), a model for any believer under conviction.`,
    verse_groups: [
      ["1-2", `David appeals first to God's mercy and lovingkindness, not to excuses: "Have mercy upon me, O God... blot out my transgressions... wash me... cleanse me from my sin." Three verbs—blot out, wash, cleanse—show sin as a stain needing removal from without, not a flaw he can scrub away himself.`],
      ["3-6", `He acknowledges his transgression is ever before him, confesses he has sinned "against thee only," and traces guilt back to conception ("shapen in wickedness"), while affirming God desires truth in the inward parts. True repentance owns sin fully and welcomes God's inward searching rather than hiding it.`],
      ["7-9", `"Purge me with hyssop, and I shall be clean; wash me, and I shall be whiter than snow." The hyssop recalls Passover and cleansing rites—forgiveness has always come through blood and washing, not self-effort. He asks to hear joy and gladness again and for God to hide His face from his sins, not from him.`],
      ["10-12", `The heart of the psalm: "Create in me a clean heart, O God; and renew a right spirit within me." "Create" is the word for making from nothing—only God can make a new heart. He pleads not to be cast away, for the Holy Spirit to remain, and for restored "joy of thy salvation," showing that assurance, not just forgiveness, had been lost.`],
      ["13-15", `Restoration will bear fruit: "Then will I teach transgressors thy ways... sinners shall be converted unto thee." He also asks deliverance from bloodguiltiness, promising his tongue will sing of God's righteousness. Forgiven sinners become useful witnesses to others.`],
      ["16-19", `God desires no mere ritual sacrifice but "a broken spirit... a broken and a contrite heart." David prays for Zion's good, that right sacrifices might again be offered—showing personal repentance cares about the wider community of worship, not only private relief.`],
    ],
    meaning: `Psalm 51 teaches that true repentance combines unflinching confession with confident appeal to God's mercy alone. Forgiveness and inward renewal are both gifts only God can give—cleansing (vv. 1–9) and re-creation of the heart (vv. 10–12)—and both issue in restored joy, usefulness, and worship (vv. 13–19). The psalm refuses cheap grace and refuses despair, holding both together.`,
    application: `When conviction comes, follow David's order: name the sin specifically before God rather than managing your image before people. Ask for a created clean heart, not merely better behavior—only God re-makes the inward man. Expect restored usefulness, not just relief: forgiven people teach, sing, and serve. Remember God is not looking for elaborate performance to earn back favor, but a broken and contrite heart, which He never despises.`,
    questions: [
      `Where do you tend to minimize or explain away sin rather than confess it as David does in verses 3–6?`,
      `What would it look like to ask God to "create" something new in your heart rather than just try harder?`,
      `Who might benefit if your experience of God's mercy turned into teaching or encouraging others, the way verse 13 describes?`,
    ],
  },
  52: {
    title: `The Green Olive Tree`,
    subtitle: `I am like a green olive tree in the house of God`,
    context: `Superscription connects this to Doeg the Edomite's betrayal of David to Saul (1 Sam 21–22), when Doeg reported that the priest Ahimelech had helped David, leading to the priests' slaughter. Henry reads the psalm as a rebuke to the "mighty man" who boasts in mischief and deceit, contrasted with the psalmist's quiet trust. MacArthur-style notes highlight the wisdom-psalm shape: a wicked man's doom versus the righteous man's rootedness, echoing Psalm 1's two ways.`,
    verse_groups: [
      ["1-4", `"Why boastest thou thyself in mischief, O mighty man?... Thy tongue deviseth mischiefs; like a sharp razor, working deceitfully." Doeg's crime was a lying tongue used for advantage and violence dressed as loyalty. Boasting in evil while God's goodness continues is folly, not strength.`],
      ["5-7", `God's answer is certain ruin: He "shall likewise destroy thee for ever," pluck him from his dwelling, and "root thee out of the land of the living." The righteous will see, fear, and laugh at one who trusted in riches and strengthened himself in wickedness rather than in God.`],
      ["8-9", `In contrast David says, "I am like a green olive tree in the house of God: I trust in the mercy of God for ever and ever." He resolves to praise God forever for what He has done and to wait on His name, since it is good, before the saints.`],
    ],
    meaning: `The psalm sets two lives side by side—the boasting, deceitful "mighty man" rooted out like a dead tree, and the trusting believer flourishing like a green olive planted in God's own house. Security and fruitfulness come from where, and in whom, a life is rooted, not from cunning or power.`,
    application: `Betrayal and slander can tempt you either toward despair or toward matching the enemy's tactics; instead, entrust judgment to God as David does. Examine whether your security rests on cleverness, wealth, or connections ("mighty man") or on being planted in God's house. Let long-term trust ("for ever and ever") shape a life of patient, visible fruitfulness rather than short-term maneuvering.`,
    questions: [
      `Where have you seen someone "boast in mischief" and prosper for a season—how does this psalm reframe that?`,
      `What would it mean this week to be "like a green olive tree in the house of God" rather than anxiously self-reliant?`,
      `How can you wait on God's name "for it is good" in a situation where vindication feels slow?`,
    ],
  },
  53: {
    title: `The Fool Hath Said in His Heart`,
    subtitle: `The fool hath said in his heart, There is no God`,
    context: `Psalm 53 closely parallels Psalm 14, with small variations (using "Elohim" for God throughout and a different ending about the enemy). Henry notes the repetition itself is instructive—universal depravity needed restating, and God repeats truths for our slow hearts. MacArthur-style notes read "fool" as moral, not merely intellectual, folly: practical atheism that fuels corruption.`,
    verse_groups: [
      ["1-3", `"The fool hath said in his heart, There is no God. Corrupt are they, and have done abominable iniquity." God looks down from heaven and finds none who understands, none who seeks Him—"they are all together become filthy." Denial of God is the root of universal corruption, not merely a private opinion.`],
      ["4-5", `"Have the workers of iniquity no knowledge? who eat up my people..." they call not upon God, yet great fear will overtake them when God scatters the bones of besiegers—shame comes because God despises them. Judgment falls even on those who feel secure in oppression.`],
      ["6", `"Oh that the salvation of Israel were come out of Zion! ...God bringeth back the captivity of his people." The psalm ends turning from complaint to hope for God-given deliverance and communal joy.`],
    ],
    meaning: `Denying God is not neutral; it corrupts conduct and community. Yet the psalm does not end in cynicism—it closes longing for salvation "out of Zion," pointing every generation toward the deliverance only God can bring for a fallen people.`,
    application: `Watch for practical atheism in yourself—living as if God does not see, even while professing belief. Let this psalm shape compassion, not superiority, toward a corrupt culture, since Scripture says none does good apart from grace. Let longing for God's salvation, not mere social critique, be your final response to evil in the world.`,
    questions: [
      `In what areas of life are you tempted to live as if "there is no God," even without saying it?`,
      `How does verse 3's universal indictment shape the way you view people who seem far from God?`,
      `What would it look like to genuinely long, like verse 6, for God's saving work rather than just complain about corruption?`,
    ],
  },
  54: {
    title: `Save Me by Thy Name`,
    subtitle: `Save me, O God, by thy name`,
    context: `Superscription ties this to the Ziphites who betrayed David's hiding place to Saul (1 Sam 23:19; 26:1). It is a short, urgent psalm of a man surrounded by treacherous informants, moving quickly from plea to praise. Henry highlights that David appeals to God's "name"—His revealed character—rather than to his own merit or strength.`,
    verse_groups: [
      ["1-3", `"Save me, O God, by thy name... strangers are risen up against me, and oppressors seek after my soul." Betrayal by supposed countrymen who "have not set God before them" is the crisis; the plea rests entirely on who God is, not on David's cause.`],
      ["4-5", `Confidence follows swiftly: "Behold, God is mine helper: the Lord is with them that uphold my soul." David asks God to "reward evil unto mine enemies" in His truth—entrusting justice to God rather than taking it himself.`],
      ["6-7", `He vows a freewill offering and promises to praise God's name, "for it is good," because his eye "hath seen his desire upon mine enemies"—deliverance already realized in confident anticipation.`],
    ],
    meaning: `When surrounded by betrayal, the ground for hope is God's own name and character, not personal innocence or strength. Prayer here moves rapidly from crisis to certainty of help, modeling how quickly trust can turn desperation into praise.`,
    application: `When people you expected to be safe betray or expose you, appeal to who God is rather than rehearsing the injustice. Let vows of thanksgiving be made even while still waiting on deliverance, as an act of faith. Leave repayment of evildoers to God's justice rather than orchestrating it yourself.`,
    questions: [
      `Who has played the role of the "Ziphites" in your life, and how does this psalm shape your response to them?`,
      `What does it mean practically to "save me… by thy name" rather than by your own strategy or strength?`,
      `How quickly do you move from crisis to praise, and what would help you trust God's help more readily?`,
    ],
  },
  55: {
    title: `Cast Thy Burden Upon the Lord`,
    subtitle: `Cast thy burden upon the LORD, and he shall sustain thee`,
    context: `A psalm of David in deep personal anguish, made worse because the chief enemy is "mine own familiar friend" who broke covenant (traditionally linked with Absalom's revolt and the betrayal of a trusted counselor). Henry notes the psalm's rare emotional intensity—longing to flee like a dove—and its turn from horror at betrayal to settled trust. MacArthur-style notes flag verses 12–14 as an Old Testament anticipation of the pain of intimate betrayal, later echoed in Christ's own experience with Judas.`,
    verse_groups: [
      ["1-3", `"Attend unto me, and hear me: I mourn in my complaint... for the voice of the enemy, because of the oppression of the wicked." David's distraction and anguish are given full voice; he does not suppress the pain of being cast down under enemy pressure.`],
      ["4-8", `"My heart is sore pained within me... fearfulness and trembling are come upon me... Oh that I had wings like a dove! for then would I fly away, and be at rest." The longing to escape entirely into the wilderness shows how crushing this pressure has become—an honest, almost desperate wish for relief.`],
      ["9-11", `He prays for the destruction and confusion of his enemies ("destroy… divide their tongues") and describes the city itself as full of violence, strife, deceit, and mischief within its own walls—corruption has infected the whole community, not just isolated enemies.`],
      ["12-14", `The sharpest wound: "It was not an enemy that reproached me… but it was thou, a man mine equal, my guide, and mine acquaintance… We took sweet counsel together." Betrayal by an intimate friend cuts deeper than open hostility ever could.`],
      ["15-19", `David prays that death seize such betrayers, "for wickedness is in their dwellings," while he himself will call upon God and be saved—praying "evening, and morning, and at noon," confident that "the Lord shall hear my voice."`],
      ["20-23", `The friend "hath put forth his hands against such as be at peace with him," his words smoother than oil yet war in his heart. The psalm's climax: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved." Bloody and deceitful men will not live out half their days, but David closes, "I will trust in thee."`],
    ],
    meaning: `Betrayal by a trusted intimate produces a uniquely crushing grief that Scripture does not minimize; yet the psalm's resolution is not escape (the dove's wings) but transferring the crushing weight onto the Lord, who sustains and will not let the righteous be permanently moved.`,
    application: `When a close friend, colleague, or family member betrays trust, let this psalm validate that the pain is uniquely severe—do not feel guilty for how deeply it hurts. Resist the temptation to either flee everything or take personal vengeance; instead literally "cast" the burden—name it in prayer and release management of the outcome to God. Build a rhythm of prayer ("evening, and morning, and at noon") especially through seasons of relational betrayal.`,
    questions: [
      `Have you experienced the specific pain of verses 12–14—betrayal by "mine own familiar friend"—and how did you respond?`,
      `What burden do you need to consciously "cast… upon the LORD" today rather than keep carrying?`,
      `How could praying at set times (morning, noon, evening) help you through a current season of hurt?`,
    ],
  },
  56: {
    title: `What Time I Am Afraid`,
    subtitle: `What time I am afraid, I will trust in thee`,
    context: `Superscription recalls when the Philistines took David in Gath (1 Sam 21:10–15), a time of real physical danger and fear. Henry admires the psalm's repeated refrain turning fear directly into trust rather than denying fear exists. MacArthur-style notes highlight verse 8's tender image of God recording tears "in a bottle," showing intimate divine attentiveness to suffering.`,
    verse_groups: [
      ["1-4", `"Be merciful unto me, O God: for man would swallow me up... What time I am afraid, I will trust in thee." Constant pressure from enemies who "wrest" his words does not stop him from choosing trust as his default response to fear, since "in God I will praise his word."`],
      ["5-7", `They mark his steps and wait for his soul as those lying in wait; David asks God to render judgment on such wickedness, refusing to let their scheming go unanswered before God.`],
      ["8-11", `Tender assurance: "Thou tellest my wanderings: put my tears into thy bottle: are they not in thy book?" God's intimate record of suffering grounds renewed confidence: "In God have I put my trust: I will not be afraid what man can do unto me."`],
      ["12-13", `Vows made in distress will be paid in praise, for God "hast delivered my soul from death"—not merely from danger, but so he may "walk before God in the light of the living."`],
    ],
    meaning: `Fear and trust are not mutually exclusive; the mature response to real danger is naming the fear honestly and then deliberately choosing trust, resting on the fact that God notices and records every tear.`,
    application: `When afraid, do not pretend otherwise—say "I am afraid" honestly to God, then add David's resolve: "I will trust in thee." Let the truth that God keeps your tears "in a bottle" shape how you process grief; nothing is wasted or unseen. Follow through on vows made in crisis once deliverance comes, rather than letting gratitude fade with the danger.`,
    questions: [
      `What situation currently makes you say, "What time I am afraid"—and how could you consciously add "I will trust in thee"?`,
      `How does it change your view of suffering to know God "tellest" your wanderings and keeps your tears "in a bottle"?`,
      `Is there a vow or promise you made to God in a hard season that you still need to fulfill now that relief has come?`,
    ],
  },
  57: {
    title: `My Heart Is Fixed`,
    subtitle: `God shall send forth his mercy and truth`,
    context: `Superscription places this "when he fled from Saul in the cave" (1 Sam 22 or 24). David is hemmed in by enemies pictured as lions and hunters, yet the psalm rises into some of the most exuberant praise in the Psalter, closing with the same refrain as Psalm 108. Henry notes the movement from "my soul is among lions" to "awake, psaltery and harp" as a model of worship overtaking fear.`,
    verse_groups: [
      ["1-3", `"Be merciful unto me, O God... my soul trusteth in thee: yea, in the shadow of thy wings will I make my refuge." He waits until calamities pass, calling to "the most high God," confident that "God shall send forth his mercy and truth" to perform all things for him.`],
      ["4-6", `Danger is vivid: "My soul is among lions... their teeth spears and arrows... they had prepared a net for my steps." Yet even surrounded by predators and traps, his soul is bowed down but not destroyed, and he anticipates their own snare consuming them.`],
      ["7-9", `Resolve breaks into song: "My heart is fixed, O God, my heart is fixed: I will sing and give praise... Awake up, my glory; awake, psaltery and harp: I myself will awake early." He commits to praising God among the peoples and nations, not privately only.`],
      ["10-11", `"For thy mercy is great above the heavens, and thy truth unto the clouds. Be thou exalted, O God, above the heavens: let thy glory be above all the earth." The closing doxology lifts the entire psalm's gaze from personal danger to God's cosmic glory.`],
    ],
    meaning: `Even in a literal cave, surrounded by lion-like enemies, the fixed heart chooses praise as an act of will, not merely a feeling—and that praise widens from private refuge to public worship of God's mercy and glory above all the earth.`,
    application: `In tight, dangerous, or confined seasons, practice saying "my heart is fixed" as a decision, not waiting for circumstances to justify praise. Let refuge be found "in the shadow of his wings" rather than in escaping every threat first. Consider how your private trust in hardship might become public praise that encourages others.`,
    questions: [
      `What "cave"—a confined, pressured season—are you currently in, and what would it mean to fix your heart in praise there?`,
      `How does verse 1's image of refuge "in the shadow of thy wings" shape your prayer today?`,
      `Where could your private trust in God become more visible praise "among the people," as verse 9 describes?`,
    ],
  },
  58: {
    title: `Break Their Teeth, O God`,
    subtitle: `Break their teeth, O God, in their mouth`,
    context: `A psalm confronting corrupt judges who "weigh violence" instead of righteousness, likely from David's experience of unjust rulers or courts. Henry treats the vivid imprecations (broken teeth, melting snails, untimely fruit) as poetic imagery for the collapse of organized wickedness under God's judgment, not literal cruelty to be imitated. MacArthur-style notes read verses 10–11 as assurance that visible justice vindicates God's moral government of the world.`,
    verse_groups: [
      ["1-2", `"Do ye indeed speak righteousness, O congregation?... ye weigh the violence of your hands." Corrupt leaders are addressed directly—injustice dressed as deliberation, violence carefully "weighed" rather than restrained.`],
      ["3-5", `The wicked are described as estranged from the womb, going astray "as soon as they be born," their venom likened to a serpent's, deaf to charming like the adder—a picture of deep-seated, willful corruption resistant to correction.`],
      ["6-9", `The famous imprecation: "Break their teeth, O God, in their mouth... Let them melt away as a snail... let them not see the sun." These are prayers that predatory power be disarmed and rendered harmless, not appeals for random cruelty.`],
      ["10-11", `"The righteous shall rejoice when he seeth the vengeance... Verily there is a reward for the righteous: verily he is a God that judgeth in the earth." Visible justice becomes cause for worship, confirming that God actively governs history, not merely eternity.`],
    ],
    meaning: `When corrupt power seems entrenched and untouchable, Scripture permits honest prayer for its disarming, grounded in confidence that God actively "judgeth in the earth"—justice is not only a future hope but a present divine activity.`,
    application: `Bring specific, corrupt structures or leaders before God honestly rather than suppressing anger at injustice; the psalm gives permission for strong prayer against organized evil. Resist despair that wickedness is permanent by remembering "verily there is a reward for the righteous." Let confirmed instances of justice in your own life or history become occasions of worship, not just relief.`,
    questions: [
      `What corrupt system or unjust "judge" in your world do you need to bring honestly before God, as this psalm does?`,
      `How does verse 11's claim that God actively "judgeth in the earth" challenge cynicism about justice ever arriving?`,
      `Where have you seen a small "reward for the righteous" that could become an occasion for praise?`,
    ],
  },
  59: {
    title: `Deliver Me from Mine Enemies`,
    subtitle: `Deliver me from mine enemies, O my God`,
    context: `Superscription connects this to Saul's men surrounding David's house to kill him (1 Sam 19:11). The psalm alternates between describing prowling enemies "like a dog" circling the city at night and confident declarations of God as defense and refuge. Henry notes the refrain repeated with growing certainty—from watching enemies at evening to singing of God's power in the morning.`,
    verse_groups: [
      ["1-5", `"Deliver me from mine enemies, O my God... defend me from them that rise up against me." Mighty men gather without cause; David protests his innocence and calls on the "LORD God of hosts, the God of Israel" to awake, behold, and visit all the heathen.`],
      ["6-10", `The enemies are pictured as dogs: "they return at evening: they make a noise like a dog, and go round about the city." Yet David will "wait upon thee," confident "the God of my mercy shall prevent me"—go before him with help.`],
      ["11-13", `A prayer that God not slay them outright but let them wander, so that people "may know that God ruleth in Jacob unto the ends of the earth"—judgment serves as public testimony, not mere personal relief.`],
      ["14-17", `The dog-like prowling returns at evening, yet the psalm closes in triumphant contrast: "But I will sing of thy power... for God is my defence, and the God of my mercy." The same nightly threat that opened in fear closes surrounded by song.`],
    ],
    meaning: `Real, prowling danger does not have the last word when God is named "defence" and "God of my mercy"—the psalm shows how the same threatening scene can be reframed by unwavering trust from crisis into praise.`,
    application: `When you feel surrounded or watched by hostility, name specific threats honestly to God rather than only enduring silently. Let "I will wait upon thee" be an active, not passive, posture—expectant rather than resigned. Practice ending prayer, even mid-crisis, with declared trust ("I will sing of thy power") rather than only petition.`,
    questions: [
      `What "dogs… round about the city" (recurring threats or anxieties) circle you at "evening," and how do you usually respond?`,
      `How does calling God your "defence" and "the God of my mercy" reframe a current fear?`,
      `What would it look like to move, like this psalm, from crisis language in the morning to song by evening?`,
    ],
  },
  60: {
    title: `Thou Hast Given a Banner`,
    subtitle: `Thou hast given a banner to them that fear thee`,
    context: `Superscription ties this to David's wars with Syria and Edom (2 Sam 8; 1 Chron 18), specifically a season when Israel suffered an initial setback ("thou hast been displeased… thou hast broken us down") before eventual victory. Henry treats it as a national lament turning into confident claim on God's promises regarding the land. MacArthur-style notes highlight verses 6–8 as God's own oracle asserting sovereign ownership of the tribes and neighboring nations.`,
    verse_groups: [
      ["1-3", `"O God, thou hast cast us off, thou hast scattered us... thou hast made the earth to tremble... heal the breaches thereof." National defeat is read theologically as divine displeasure, not mere bad luck, calling for God's own healing of what He has broken.`],
      ["4-5", `Yet even amid discipline, "Thou hast given a banner to them that fear thee, that it may be displayed because of the truth." A rallying sign of hope is granted so that "thy beloved" may be delivered—chastening does not cancel covenant love.`],
      ["6-8", `God's own oracle of ownership: "I will divide Shechem... Gilead is mine, and Manasseh is mine... Moab is my washpot... over Philistia will I triumph." Sovereign claim over Israel's tribes and hostile neighbors grounds any hope of victory.`],
      ["9-12", `The question "Who will bring me into the strong city? who will lead me into Edom?" answers itself: not human strength ("vain is the help of man") but God alone, who alone "shalt tread down our enemies," gives true valor and victory.`],
    ],
    meaning: `National setbacks under God's discipline do not erase His covenant claims or His banner of hope for those who fear Him; ultimate victory over hostile powers rests entirely on God's sovereign ownership and strength, not human alliance or might.`,
    application: `When corporate or personal defeat feels like divine displeasure, ask God to "heal the breaches" rather than only analyzing the loss strategically. Look for the "banner" God has given—some sign of hope He grants even amid discipline—and rally around it. Recognize that "vain is the help of man" in your hardest battles; let dependence on God replace confidence in human strategy alone.`,
    questions: [
      `Where have you experienced a setback that felt like discipline, and how might you pray verses 1–3's honest lament?`,
      `What "banner"—sign of hope or rallying truth—has God given you in a hard season?`,
      `In what battle are you currently relying on "the help of man" more than on God's promised strength?`,
    ],
  },
  61: {
    title: `The Rock That Is Higher Than I`,
    subtitle: `Lead me to the rock that is higher than I`,
    context: `A shorter psalm of David, likely written in exile or distance from the sanctuary (v. 2, "from the end of the earth"), asking for shelter and long life for the king, suggesting either David's own reign or intercession for it. Henry highlights the image of the "rock higher than I"—a refuge beyond one's own reach or strength, requiring God to lead him there.`,
    verse_groups: [
      ["1-2", `"Hear my cry, O God... From the end of the earth will I cry unto thee, when my heart is overwhelmed: lead me to the rock that is higher than I." Distance and being overwhelmed do not prevent prayer; instead they intensify the plea for a refuge beyond his own strength to reach.`],
      ["3-5", `Confidence in past faithfulness: "Thou hast been a shelter for me, and a strong tower from the enemy." He resolves to abide in God's tabernacle forever and trust "in the covert of thy wings," recalling vows already made and heard.`],
      ["6-8", `Intercession, likely for the king: "Thou wilt prolong the king's life... mercy and truth, which may preserve him." He vows to "sing praise to thy name for ever" and "daily perform" his vows in ongoing worship, not one-time relief.`],
    ],
    meaning: `When overwhelmed and far from familiar supports, true refuge is a "rock higher than I"—beyond self-generated strength—that God alone leads a person to; and that personal refuge extends naturally into ongoing worship and intercession for others, such as a king or leader.`,
    application: `When emotionally or geographically distant from support, remember prayer still reaches God "from the end of the earth." Ask specifically to be led to a refuge "higher" than your own coping strategies. Let personal experience of shelter turn into intercession—pray for leaders' preservation the way David does here, not only for your own needs.`,
    questions: [
      `When you feel "overwhelmed" and distant from support, how does verse 2's prayer to be led to a "higher" rock guide you?`,
      `What past experiences of God as "shelter" and "strong tower" can you draw on now?`,
      `Who in leadership over you could you intercede for this week, as David does for the king?`,
    ],
  },
  62: {
    title: `Wait Thou Only Upon God`,
    subtitle: `My soul, wait thou only upon God`,
    context: `A meditation of David on exclusive trust amid enemies who plot to topple him ("a bowing wall… a tottering fence"), likely from a season of political instability. Henry stresses the repeated word "only"—God alone as rock, salvation, and refuge—as the psalm's central discipline against divided trust.`,
    verse_groups: [
      ["1-4", `"Truly my soul waiteth upon God: from him cometh my salvation. He only is my rock and my salvation." Enemies seek to destroy him "as a bowing wall," delighting in lies and blessing with the mouth while cursing inwardly—instability all around, met by settled trust.`],
      ["5-8", `He preaches to his own soul: "My soul, wait thou only upon God... He is my rock... Trust in him at all times; ye people, pour out your heart before him." Public exhortation follows private discipline—trust is meant to be modeled, not only privately held.`],
      ["9-12", `"Men of low degree are vanity, and men of high degree are a lie... trust not in oppression... if riches increase, set not your heart upon them." Power belongs to God, and to Him alone belongs mercy—closing with the double truth heard "twice," that strength and steadfast love both come from Him.`],
    ],
    meaning: `The word "only" is the psalm's hinge: salvation, rock, and trust must rest exclusively in God—not divided among human status, oppression's advantage, or increasing riches—because power and mercy both belong solely to Him.`,
    application: `Notice where you quietly split trust between God and something else and practice saying "he only" specifically about that thing. Preach truth to your own soul as David does (v. 5), rather than waiting for feelings to catch up. When riches or influence increase, deliberately "set not your heart upon them," redirecting gratitude back to God's power and mercy.`,
    questions: [
      `Where in your life is trust currently divided rather than resting "only" upon God?`,
      `What would it look like this week to "pour out your heart before him" as verse 8 urges?`,
      `If your riches or influence increased, how would you guard against setting your heart on them (v. 10)?`,
    ],
  },
  63: {
    title: `Early Will I Seek Thee`,
    subtitle: `Early will I seek thee`,
    context: `Superscription places David "in the wilderness of Judah," likely fleeing Saul or Absalom, physically thirsty in a literal dry and barren land. Henry notes how physical thirst becomes the doorway to spiritual longing—desire for God expressed in bodily terms. MacArthur-style notes point to the psalm's structure moving from longing (1–2), to satisfaction remembered (3–5), to nighttime meditation (6–8), to confidence over enemies (9–11).`,
    verse_groups: [
      ["1-2", `"O God, thou art my God; early will I seek thee: my soul thirsteth for thee... in a dry and thirsty land, where no water is." Physical deprivation in the wilderness intensifies, rather than dampens, spiritual desire—he seeks God's power and glory as once seen in the sanctuary.`],
      ["3-5", `"Because thy lovingkindness is better than life, my lips shall praise thee... my soul shall be satisfied as with marrow and fatness." Even lacking literal water, he is more filled by God's lovingkindness than by any physical provision, praising with lifted hands.`],
      ["6-8", `Meditation continues into sleeplessness: "When I remember thee upon my bed, I meditate on thee in the night watches... My soul followeth hard after thee: thy right hand upholdeth me." Longing does not fade in darkness but turns to sustained, pursuing meditation.`],
      ["9-11", `Enemies "that seek my soul to destroy it" will fall by the sword and become "a portion for foxes," while the king will rejoice in God and every true worshiper will glory, but "the mouth of them that speak lies shall be stopped." Confidence in vindication closes the psalm.`],
    ],
    meaning: `Genuine thirst for God is not incompatible with literal scarcity—wilderness deprivation can become the very occasion for the deepest satisfaction, praise, and pursuing meditation, because God's lovingkindness outweighs life itself.`,
    application: `In a literal or figurative "dry and thirsty land," let physical longing point you toward greater spiritual thirst rather than only complaint. Practice remembering God specifically "upon my bed" and in "night watches" when sleep is elusive. Let satisfaction in God's lovingkindness, not changed circumstances, be the goal you actually seek "early."`,
    questions: [
      `What "dry and thirsty land" are you in right now, and how might it become an occasion to seek God "early"?`,
      `How can nighttime restlessness become meditation on God rather than only anxiety, as in verses 6–8?`,
      `In what specific way is God's "lovingkindness" currently "better than life" for you?`,
    ],
  },
  64: {
    title: `Hide Me from the Secret Counsel of the Wicked`,
    subtitle: `Hide me from the secret counsel of the wicked`,
    context: `A prayer of David against conspirators who plot in secret, using sharpened words like arrows and confident that no one sees their schemes. Henry contrasts the hidden plotting of the wicked with the hidden protection David seeks from God—both operate unseen, but only one succeeds. MacArthur-style notes emphasize the sudden reversal at verse 7: what the wicked shoot secretly, God shoots back suddenly and publicly.`,
    verse_groups: [
      ["1-4", `"Hear my voice, O God... hide me from the secret counsel of the wicked... Who whet their tongue like a sword, and bend their bows to shoot their arrows, even bitter words." Slander and conspiracy are described as literal weapons aimed "privily at the perfect," ambushing the innocent without warning.`],
      ["5-6", `"They encourage themselves in an evil matter: they commune of laying snares privily; they say, Who shall see them?... they search out iniquity; they accomplish a diligent search." Wickedness here is organized and confident of concealment, presuming no divine witness.`],
      ["7-10", `The reversal: "But God shall shoot at them with an arrow; suddenly shall they be wounded." Their own tongue causes them to fall; all who see will fear and declare God's work; the righteous will be glad in the Lord, trust in Him, and glory.`],
    ],
    meaning: `Secret conspiracies that presume "Who shall see them?" forget the God who sees in secret and shoots suddenly in reply—hidden wickedness eventually meets hidden justice, turning public fear into public praise.`,
    application: `When you are the target of hidden slander or scheming, ask God specifically to "hide" you rather than trying to expose or out-maneuver every plot yourself. Remember that presumed secrecy is always an illusion before God. Let confidence in God's sudden justice free you to be glad and trust rather than obsessively monitoring conspirators.`,
    questions: [
      `Have you experienced something like "secret counsel" or hidden opposition against you—how does this psalm shape your response?`,
      `Where might you be tempted to "search out iniquity" against others in ways this psalm condemns?`,
      `How does trusting God's sudden reversal (v. 7) change how much energy you spend managing hidden threats?`,
    ],
  },
  65: {
    title: `Praise Waiteth for Thee`,
    subtitle: `Praise waiteth for thee, O God, in Zion`,
    context: `A harvest and covenant psalm blending forgiveness of sin, God's power over creation, and His generous provision through rain and harvest. Henry treats it as moving from personal and national atonement (1–4) to cosmic sovereignty (5–8) to agricultural blessing (9–13), showing that the God who forgives is the same God who governs nature and feeds nations.`,
    verse_groups: [
      ["1-4", `"Praise waiteth for thee, O God, in Zion... thou that hearest prayer... iniquities prevail against me: as for our transgressions, thou shalt purge them away." Access to God's courts is framed as pure gift—blessed is the one God chooses and satisfies with the goodness of His house.`],
      ["5-8", `"By terrible things in righteousness wilt thou answer us, O God of our salvation... Who stilleth the noise of the seas... the outgoings of the morning and evening to rejoice." Awe-inspiring acts of judgment and creation-control cause even the ends of the earth to fear and the farthest dawn and dusk to rejoice.`],
      ["9-13", `"Thou visitest the earth, and waterest it... thou preparest them corn... the pastures are clothed with flocks; the valleys also are covered over with corn: they shout for joy, they also sing." Agricultural abundance is described as God's personal visitation and generosity, evoking a creation bursting into song at His care.`],
    ],
    meaning: `The same God who forgives sin and answers prayer in Zion also governs raging seas and tumultuous peoples, and personally visits the earth to water it and clothe valleys with grain—forgiveness, sovereignty, and provision are one seamless expression of His character.`,
    application: `Let corporate worship be something you actively anticipate, not merely attend. When overwhelmed by chaotic circumstances, remember the same God who stills nations governs your storm. Notice ordinary provision—weather, harvest, daily bread—as personal divine visitation worthy of the joyful response described in verse 13.`,
    questions: [
      `How does linking forgiveness of sin (vv. 3–4) with God's rule over nature (vv. 5–8) deepen your view of His character?`,
      `Where do you need to trust the God who "stilleth the noise of the seas" amid a current chaotic situation?`,
      `What ordinary provision in your life could you receive today as God's personal "visitation," as in verses 9–13?`,
    ],
  },
  66: {
    title: `Come and See the Works of God`,
    subtitle: `Come and see the works of God`,
    context: `A communal thanksgiving psalm inviting "all ye lands" to praise God for His awesome deeds and for personally answering the psalmist's own prayer after testing. Henry notes the shift from national praise (1–12) to individual testimony and vows fulfilled (13–20), a pattern of public worship rooted in private experience.`,
    verse_groups: [
      ["1-4", `"Make a joyful noise unto God, all ye lands... say unto God, How terrible art thou in thy works!... all the earth shall worship thee." Universal, exuberant praise is called for on the basis of God's fearsome, wonder-working reputation among all nations.`],
      ["5-7", `"Come and see the works of God... He turned the sea into dry land: they went through the flood on foot... He ruleth by his power for ever." The Exodus is remembered as ongoing proof of present, continuing divine government over rebellious nations.`],
      ["8-12", `"O bless our God, ye people... which holdeth our soul in life... thou, O God, hast proved us: thou hast tried us, as silver is tried... thou broughtest us out into a wealthy place." Testing and affliction are acknowledged honestly as God's own refining process, not meaningless suffering, ending in abundance.`],
      ["13-15", `"I will go into thy house with burnt offerings: I will pay thee my vows... I will offer bullocks with goats." Private vows made during trouble are now fulfilled publicly with costly, specific worship.`],
      ["16-20", `"Come and hear, all ye that fear God, and I will declare what he hath done for my soul... Verily God hath heard me... Blessed be God, which hath not turned away my prayer, nor his mercy from me." Personal testimony becomes public instruction, closing on assurance that sincere prayer is never ultimately refused.`],
    ],
    meaning: `National memory of God's mighty acts and personal testimony of answered prayer reinforce each other; testing by fire and water is acknowledged as God's refining work, and it issues in specific, costly worship and public testimony meant to instruct others who fear God.`,
    application: `Recount concrete "works of God"—corporately remembered and personally experienced—as a discipline of praise, not vague sentiment. When reflecting on hard seasons, consider whether God was refining you like silver, not abandoning you. Turn private vows made in trouble into specific, fulfilled acts of worship, and be willing to "declare" to others what God has done for your soul.`,
    questions: [
      `What specific "works of God"—corporate or personal—could you "come and see" and recount today?`,
      `Looking back at a season of testing ("fire and water"), can you identify how God was refining you like silver?`,
      `Is there a vow or promise made during a hard season that you still need to "pay," as verse 13 describes?`,
    ],
  },
  67: {
    title: `Let the Nations Praise Thee`,
    subtitle: `God be merciful unto us, and bless us`,
    context: `A brief harvest thanksgiving with strong missionary breadth, echoing the Aaronic blessing (Num 6:24–26) in its opening line and repeatedly calling all peoples and nations to praise God. Henry reads it as showing Israel's blessing was always meant to overflow toward "all the ends of the earth," not remain self-contained.`,
    verse_groups: [
      ["1-3", `"God be merciful unto us, and bless us... That thy way may be known upon earth, thy saving health among all nations. Let the people praise thee, O God; let all the people praise thee." National blessing is explicitly requested for the sake of global witness, not mere comfort.`],
      ["4-7", `"O let the nations be glad, and sing for joy: for thou shalt judge the people righteously... Then shall the earth yield her increase; and God, even our own God, shall bless us... and all the ends of the earth shall fear him." Harvest abundance and universal reverence are woven together as evidence of God's righteous, global governance.`],
    ],
    meaning: `Personal and national blessing exist to make God's "way" and "saving health" known to all nations—harvest and gladness are not ends in themselves but occasions for the whole earth to fear and praise the God who governs righteously.`,
    application: `When you experience blessing, ask how it might make God's "way" known beyond yourself, not stop with private gratitude. Pray specifically for "the nations" and "all the people" to be glad in God, widening intercession beyond personal or local concerns. Let increase in your own life become a testimony point toward God's righteous governance, not just personal comfort.`,
    questions: [
      `How might a current blessing in your life become a way to make God's "saving health" known to others?`,
      `What would it look like to pray specifically, as this psalm does, for "all the nations" rather than only your own concerns?`,
      `How does connecting harvest and increase with worldwide praise (vv. 6–7) change how you view material blessing?`,
    ],
  },
  68: {
    title: `Let God Arise`,
    subtitle: `Let God arise, let his enemies be scattered`,
    context: `A grand processional and battle hymn of David, likely composed for the ark's journey (2 Sam 6) or a national festival, tracing God's power from the Exodus and wilderness march to His enthronement in Zion and reign over all kingdoms. It is quoted in Ephesians 4:8 concerning Christ's ascension and gift-giving to the church. Henry treats it as the Old Testament's great song of God as Warrior-King who defends the weak and receives tribute from the nations; MacArthur-style notes highlight its use of ancient triumphal procession imagery culminating in worldwide praise.`,
    verse_groups: [
      ["1-6", `The psalm opens as a battle cry (echoing Num 10:35) that quickly turns tender: "Let God arise, let his enemies be scattered... Sing unto God, sing praises to his name... A father of the fatherless, and a judge of the widows, is God... God setteth the solitary in families." The same God who scatters enemies champions the fatherless, widows, and lonely.`],
      ["7-10", `"O God, when thou wentest forth before thy people... the earth shook... the heavens also dropped at the presence of God... thou, O God, hast prepared of thy goodness for the poor." The Exodus and Sinai theophany are recalled as proof of God's protective, providing presence marching ahead of His people.`],
      ["11-14", `"The Lord gave the word: great was the company of those that published it. Kings of armies did flee apace... though ye have lien among the pots, yet shall ye be as the wings of a dove covered with silver." Victory is announced and celebrated even by those who seemed passive or lowly, transformed into glittering beauty.`],
      ["15-18", `"The hill of God is as the hill of Bashan... the chariots of God are twenty thousand... Thou hast ascended on high, thou hast led captivity captive: thou hast received gifts for men." God's dwelling surpasses Bashan's great mountains; His ascension with captured spoils anticipates Christ's ascension and gift-giving (Eph 4:8).`],
      ["19-23", `"Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation... God shall wound the head of his enemies." Ongoing, daily benefit-giving is coupled with certain judgment on persistent enemies—both mercy and justice belong to this King.`],
      ["24-27", `"They have seen thy goings, O God... the singers went before, the players on instruments followed after... Bless ye God in the congregations... There is little Benjamin with their ruler, the princes of Judah... Zebulun, and... Naphtali." A vivid worship procession names specific tribes taking their place in unified national praise.`],
      ["28-31", `"Strengthen, O God, that which thou hast wrought for us... kings shall bring presents unto thee... Princes shall come out of Egypt; Ethiopia shall soon stretch out her hands unto God." Foreign nations, even former oppressors, are pictured submitting tribute to God—an early vision of Gentile inclusion in worship.`],
      ["32-35", `"Sing unto God, ye kingdoms of the earth... Ascribe ye strength unto God: his excellency is over Israel... The God of Israel is he that giveth strength and power unto his people. Blessed be God." The psalm closes with a global summons to praise the God whose strength both governs Israel and empowers His people for all that lies ahead.`],
    ],
    meaning: `God is Warrior and Father at once—scattering enemies while adopting orphans, marching through wilderness history while daily loading His people with benefits, ascending in triumph while inviting even former oppressor-nations to bring tribute. His strength is not only historical memory but present and future empowerment.`,
    application: `Let the same God who scatters enemies shape how you pray for justice, while also remembering He is "father of the fatherless… judge of the widows"—strength and tenderness belong together in His character and should in yours. Recall specific "goings" of God in your own history as fuel for present praise. Trust that God still "daily loadeth us with benefits" even when the biggest battles feel unresolved, and expect His strength to be given, not just admired, for what's ahead.`,
    questions: [
      `How does holding together God as Warrior (vv. 1, 21) and as Father of the fatherless (v. 5) shape your view of His character?`,
      `What specific "goings" of God in your past could you recall and retell as this procession psalm does?`,
      `Where do you need to trust that God will "daily" load you with benefits and give strength for a current battle?`,
    ],
  },
  69: {
    title: `The Waters Are Come In Unto My Soul`,
    subtitle: `Save me, O God; for the waters are come in unto my soul`,
    context: `One of the most extensive personal laments in the Psalter, quoted repeatedly in the New Testament of Christ's sufferings (zeal for God's house, John 2:17; hated without cause, John 15:25; gall and vinegar at the cross, Matt 27:34,48; table become a snare applied to unbelieving Israel, Rom 11:9–10). Henry reads David's own drowning distress, likely from persecution tied to zeal for the sanctuary, as a shadow of the greater sufferings of Christ, who fulfills the pattern of innocent suffering for righteousness' sake. MacArthur-style notes caution that the imprecatory section (22–28) functions as covenant-lawsuit language against persistent, unrepentant enemies of God's anointed, not personal vindictiveness.`,
    verse_groups: [
      ["1-4", `"Save me, O God; for the waters are come in unto my soul. I sink in deep mire... I am weary of my crying... They that hate me without a cause are more than the hairs of mine head." Overwhelming, drowning distress is described physically—exhaustion of voice and eyes—compounded by hatred he did not provoke.`],
      ["5-9", `"O God, thou knowest my foolishness... let not them that wait on thee, O Lord God of hosts, be ashamed for my sake... the zeal of thine house hath eaten me up." He fears his own failures might discourage other worshipers, yet the deepest cause of his suffering is devotion to God's house, not personal sin—words later applied directly to Christ.`],
      ["10-12", `"When I wept, and chastened my soul with fasting... I made sackcloth my garment... I was the song of the drunkards." Sincere spiritual discipline becomes public mockery—devotion itself invites ridicule.`],
      ["13-15", `"But as for me, my prayer is unto thee... Let not the waterflood overflow me, neither let the deep swallow me up." Amid mockery, prayer continues undeterred, pleading specifically against being overwhelmed entirely.`],
      ["16-18", `"Hear me, O LORD; for thy lovingkindness is good... hide not thy face from thy servant... draw nigh unto my soul." Appeal rests wholly on God's character, asking for nearness in the midst of distance and shame.`],
      ["19-21", `"Thou hast known my reproach, and my shame, and my dishonour... reproach hath broken my heart... they gave me gall to eat; and in my thirst they gave me vinegar to drink." God's full knowledge of his humiliation is affirmed even as the specific details become strikingly prophetic of the crucifixion.`],
      ["22-25", `"Let their table become a snare... let their eyes be darkened, that they see not... Pour out thine indignation upon them." Strong covenant-lawsuit language calls for judicial reversal on persistent, unrepentant persecutors of God's righteous sufferer.`],
      ["26-28", `"For they persecute him whom thou hast smitten... let them be blotted out of the book of the living." The imprecation escalates to ultimate exclusion for those who compound cruelty against one already afflicted by God's own hand.`],
      ["29-33", `"But I am poor and sorrowful: let thy salvation, O God, set me up... I will praise the name of God with a song... This also shall please the LORD better than an ox or bullock... the humble shall see this, and be glad." A turn to worship insists that sincere praise pleases God more than costly ritual sacrifice—present even amid unresolved suffering.`],
      ["34-36", `"Let the heaven and earth praise him, the seas... For God will save Zion, and will build the cities of Judah... they that love his name shall dwell therein." The psalm broadens from personal rescue to the certain future restoration of Zion and Judah, closing in communal hope.`],
    ],
    meaning: `Innocent suffering for zeal toward God's house—met with mockery, betrayal, and physical torment—finds its fullest meaning in Christ, who bore reproach that was not His own; yet even amid unresolved anguish, sincere praise pleases God more than sacrifice, and personal lament ultimately widens into confidence in Zion's certain restoration.`,
    application: `When devotion to God invites ridicule rather than admiration, remember David—and ultimately Christ—walked this road before you; you are not alone in being mocked for taking God seriously. Bring "waters… come in unto my soul" language honestly to God rather than minimizing overwhelming distress. Let praise remain possible even when circumstances are unresolved, since sincere worship pleases God more than any performance or sacrifice could.`,
    questions: [
      `Where has zeal for God's house or God's ways brought you reproach rather than praise, as in verses 7–9?`,
      `How does seeing this psalm fulfilled in Christ's suffering deepen your reading of your own hard seasons?`,
      `What would it look like to offer God a "song" of praise (v. 30) even while your circumstances remain like "deep waters"?`,
    ],
  },
  70: {
    title: `Make Haste, O God`,
    subtitle: `Make haste, O God, to deliver me`,
    context: `A brief, urgent psalm nearly identical to the closing verses of Psalm 40 (13–17), functioning as its own short prayer for immediate rescue from those who mock the psalmist's affliction. Henry notes its repeated urgency ("make haste") twice in five verses, modeling prayer that does not pad requests with elaborate argument when danger is pressing.`,
    verse_groups: [
      ["1-3", `"Make haste, O God, to deliver me... Let them be ashamed and confounded that seek after my soul... Let them be turned back for a reward of their shame that say, Aha, aha." The plea is immediate and specific: reversal of shame onto those who mock his affliction with cruel taunts.`],
      ["4-5", `"Let all those that seek thee rejoice and be glad in thee... But I am poor and needy: make haste unto me, O God... O LORD, make no tarrying." The psalm balances communal joy for all seekers of God with the psalmist's own acute, personal urgency, closing exactly as it began—with an unresolved plea for speed.`],
    ],
    meaning: `Some prayers are rightly brief and urgent rather than elaborate; naming yourself honestly as "poor and needy" and asking God not to "tarry" is itself a complete, faithful prayer, even without immediate resolution in the text.`,
    application: `In genuine crisis, do not feel you must construct a theologically elaborate prayer before God will listen—"make haste" is enough. Let honest neediness replace performing spiritual strength you don't currently feel. Hold together, as this psalm does, urgent personal plea and genuine joy for others who seek God, rather than letting your own need eclipse all other concern.`,
    questions: [
      `What situation right now calls for a simple, urgent "make haste, O God" rather than an elaborate prayer?`,
      `How comfortable are you admitting "I am poor and needy" honestly before God?`,
      `How can you hold together urgent personal need and genuine gladness for others who "seek" God, as verses 4–5 do?`,
    ],
  },
};
